# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='core.Estabelecimento'),
        ),
    ]
