# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161125_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='estabelecimento',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='core.Categoria'),
        ),
    ]
