# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estabelecimento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cidade',
            field=models.CharField(choices=[('E', 'Ciudad del Este'), ('P', 'Pedro Juan Caballero'), ('S', 'Salto del Guairá')], max_length=1),
        ),
    ]
