# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161112_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('website', models.URLField()),
                ('kind', models.CharField(choices=[('F', 'Anuncio Free'), ('M', 'Anuncio Medio'), ('T', 'Anuncio Top')], default='F', max_length=1)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
            },
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store'),
        ),
    ]
