# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161125_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='categorias', to='core.Categoria'),
        ),
    ]
