# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161112_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Anúncio', 'verbose_name_plural': 'Anúncios'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='img',
            field=models.URLField(default='www.maisparaguai.com/img/1/27/banners/n/89467f1c27d00b18232c15149280832d.jpg'),
            preserve_default=False,
        ),
    ]
