# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161119_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
