# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
