# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161117_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='plano',
        ),
    ]
