# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_estabelecimento_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefone', to='core.Estabelecimento'),
        ),
    ]
