# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161119_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
