# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:00
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='categoria',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='estabelecimentos', to='core.Categoria'),
        ),
    ]
