# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161209_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
