# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161209_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristica',
            old_name='valor',
            new_name='conteudo',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='logo',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='preco',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
