# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import src.core.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161209_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(upload_to=src.core.managers.path_and_rename_banner),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='logo',
            field=models.ImageField(null=True, upload_to=src.core.managers.path_and_rename_logo),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=src.core.managers.path_and_rename_fotos),
        ),
    ]
