# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import src.core.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161209_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=src.core.managers.path_and_rename_categoria),
        ),
    ]
