# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161223_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='conteudo_es',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='conteudo_pt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='titulo_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='titulo_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preco',
            name='titulo_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preco',
            name='titulo_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
