# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161223_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome_es',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome_pt',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
