# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-13 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161224_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
    ]
