# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_estabelecimento_recomendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estabelecimento'),
        ),
    ]
