# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-15 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import src.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170714_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='search_hits',
            field=models.PositiveIntegerField(default=1, verbose_name='Total de buscas acessadas'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(help_text='### ATENÇÃO - TAMANHO DA IMAGEM PRECISA SER 585x80 ###', upload_to=src.core.utils.path_and_rename_banner),
        ),
    ]
