# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170717_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
    ]
