# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-17 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.CharField(help_text='Lembrar de setar como publicado o template no Sparkpost', max_length=100, verbose_name='Nome da campanha')),
                ('template', models.CharField(max_length=100, verbose_name='Spark Template')),
                ('recipients', models.TextField(max_length=100, verbose_name='Lista de Emails')),
                ('enviado', models.BooleanField(default=False, verbose_name='Foi enviado?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('response', models.CharField(max_length=200, verbose_name='Response Spark')),
            ],
            options={
                'verbose_name': 'Envio de Newsletter',
                'verbose_name_plural': 'Envio de Newsletters',
            },
        ),
    ]
