# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-20 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroNewsLetter',
        ),
        migrations.DeleteModel(
            name='EnvioNewsLetter',
        ),
    ]
