# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.SmallIntegerField(choices=[(0, 'Tornar-se Anunciante'), (1, 'Cadastrar Empresa')], default=0, verbose_name='Tipo'),
        ),
    ]
