# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20170713_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='teste', verbose_name='Conteudo'),
            preserve_default=False,
        ),
    ]
