# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Noticia'), (1, 'Lazer Turismo')], default=0, verbose_name='categoria'),
        ),
    ]
