# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import src.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=src.posts.models.upload_location),
        ),
    ]
